//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_Calificaciones.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int ID { get; set; }
        public int EstudianteID { get; set; }
        public int MateriaID { get; set; }
        public Nullable<decimal> Calificacion1 { get; set; }
        public Nullable<decimal> Calificacion2 { get; set; }
        public Nullable<decimal> Calificacion3 { get; set; }
        public Nullable<decimal> Calificacion4 { get; set; }
        public Nullable<decimal> Examen { get; set; }
        public Nullable<decimal> TotalCalificacion { get; set; }
        public string Clasificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
